- hosts: all
  roles:
   # - join_ad
    - fail2ban
   #- cg21_repos
  vars: 
    - b2f_bantime: "30"
    - b2f_findtime: "600"
    - b2f_maxretry: "3"
    #- b2f_ignoreip:
    - b2f_destemail : dt@mailtrap.fr
    - b2f_sender : dt@mailtrap.fr
    - b2f_sendername: Fail2Ban Services
    - b2f_mta: sendmail
    - b2f_action: "%(action_mw)s"
