- hosts: all
  roles:
    - join_ad
    - fail2ban
  vars: 
    - b2f_bantime: "3600"
    - b2f_findtime: "600"
    - b2f_maxretry: "3"
    #- b2f_ignoreip:
    #- b2f_destemail :
    #- b2f_sender :
    #- b2f_sendername:
    #- b2f_mta:
    - b2f_action: "%(action_)s"
