
- hosts: all
  gather_facts: false
  connection: local
 
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
 
  # Create a VM from a template
  - name: create the VM
    vmware_guest:
      hostname: '10.18.10.95'
      username: 'root'
      password: 'rootroot123!'
      validate_certs: no
      esxi_hostname: localhost.cg21.priv
      datacenter: 'datastore1'
      folder: A_DEPLOYER
      name: '{{ inventory_hostname }}'
      state: poweredon
      guest_id: rhel7_64Guest
      annotation: "test - {{ creationdate }}"
      disk:
      - size_gb: 150
        type: thin
        datastore: 'datastore1'
      networks:
      - name: server_network
        ip: '10.18.10.199'
        netmask: 255.255.252.0
        gateway: 192.168.100.1
        dns_servers:
        - 192.168.100.10
        - 192.168.101.10
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
        - 192.168.100.10
        - 192.168.101.10
        domain : zwindler.fr
        hostname: 'localhost'
      template: tmpl-rhel-7-3-app
      wait_for_ip_address: yes
 
