---
- name: restart fail2ban (with service)
  systemd:
    state: restarted
    daemon_reload: yes
    name: fail2ban
    
- name: restart postfix (with service)
  systemd:
    state: restarted
    daemon_reload: yes
    name: postfix

# handlers file for fail2ban