---
- name: create backup folder
  shell: mkdir /tmp/repos
- name: save older configuration
  copy:
    src: /etc/yum.repos.d
    dest: /tmp/repos
- name: delete older file
  shell: rm /etc/yum.repos.d/*
- name: copy configuration
  template:
    src: remote.repo
    dest: /etc/yum.repos.d/remote.repo
    owner: root
    group: root
    mode: 0644