---
- name: create backup folder
  shell: mkdir /tmp/repos
- name: save older configuration
  copy:
    src: /etc/yum.repos.d
    dest: /tmp/repos
- name: delete older file
  shell: rm /etc/yum.repos.d/*
- name: Create new repos configuration file
  shell: touch /etc/yum.repos.d/remote.repo
