---
- name: 1. installlation des package de base
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - sssd
    - realmd
    - oddjob
    - oddjob-mkhomedir
    - adcli
    - samba-common
    - samba-common-tools
    - krb5-workstation
    - openldap-clients
    - policycoreutils-python
    state: present

- name: 2. installation et configuration du repos epel
  yum:
    name: epel-release
    state: present

- name: 3. Configuration de epel (1/2)
  replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: '(^#baseurl=http:\W{2}download.fedoraproject.org\Wpub\Wepel\W7\W\Wbasearch\n)'
    replace: 'baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch\n'
- name: 3.1 Configuration de epel (2/2)
  replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: '(metalink=ht{2}ps:\W\Wmir{2}ors.fedoraproject.org\Wmetalink\Wrepo=epel-7&arch=\Wbasearch\n)'
    replace: '#metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'

- name: 4. installation de python-pip (1/2)
  yum: 
    name: python-pip
    state: present

- name: 4.1 installation de python-pip (2/2)
  yum: 
    name: python-pip
    state: present

- name: 5. installation de expect
  pip:
    name: pexpect

- name: 6. Reboot de la machine pour appliquer les changements
  reboot:
    reboot_timeout: 3600

- name: 7. Test de connection de la machine
  shell: /bin/bash -c "realm list | grep sssd"
  register: realm_trouver
  changed_when: false
  ignore_errors: true

- name: 8. Jonction au domaine
  expect:
    command: /bin/bash -c "/usr/sbin/realm join --user="{{ user_domaine }}" "{{ domaine }}""
    responses:
      Password for *: "{{ mdp_user}}"
  when: realm_trouver is failed

- name: 9. installation de FAIL2BAN (1/2)
  yum: 
    name: fail2ban
    state: present
- name: 9.1 installation de fail2ban (2/2)
  service:
    name: fail2ban
    enabled: yes
- name: 10. Configuration de sssd pour ne pas utiliser le nom pleinement qualifié (1/3)
  replace:
    path: /etc/sssd/sssd.conf
    after: 'use_fully_qualified_names = '
    before: '\n'
    regexp: 'True'
    replace: 'False'
- name: 10.1 Configuration de sssd poir ne pas utiliser le nom pleinement qualifié (2/3)
  replace:
    path: /etc/sssd/sssd.conf
    after: 'fallback_homedir = '
    before: '\n'
    regexp: '\Whome\W{2}u\W{2}d'
    replace: ' /home/%u'
- name: 10.2 Configuration de sssd poir ne pas utiliser le nom pleinement qualifié (3/3)
  service:
    name: sssd
    state: restarted
- name: 11. Ajout du groupe ad pour les droit sudoers 
  lineinfile:
    dest: /etc/sudoers
    line: '%GDL-CDS-ADM-TCENTOSAD01        ALL=(ALL)       ALL'
    insertafter: '^root'
