---
- name: Configuration du template et copy sur le client
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644


- name: installation des paquets pour postfix
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - postfix
    - cyrus-sasl-plain
    - mailx
    state: present

- name: Configuration PostFix (1/)
  template:
    src: main.cf
    dest: /etc/postfix
    owner: root
    group: root
    mode: 0644

- name: Configuration PostFix (1/)
  template:
    src: sasl_passwd
    dest: /etc/postfix
    owner: root
    group: root
    mode: 0644


- name: Configuration PostFix (1/)
  template:
    src: tmp_cmd.sh
    dest: /etc/postfix
    owner: root
    group: root
    mode: 0644

- name: Execute the script
  command: sh /etc/postfix/tmp_cmd.sh

- name: restart postfix (with service)
  systemd:
    state: restarted
    daemon_reload: yes
    name: postfix
    
- name: restart postfix (with service)
  systemd:
    state: restarted
    daemon_reload: yes
    name: fail2ban
# tasks file for fail2ban